### ISSUE TITLE
LensletSize_pix in LFReadESLF

### ISSUE THREAD

**Issue by moha23** [doda42/LFToolbox#13]
Hi, first of thank you for this toolbox, it has been very helpful! 
In LFReadESLF the default value for LensletSize_pix is (14,14). I am unable to confirm if that's the lenslet size for all Lytro illums? The data at http://lightfields.stanford.edu/LF2016.html seems to be read correctly with this default value, but the raw light field from our Lytro Illum seems to have (15,15) views. Am I correct to assume that different Lytro illums can have different number of pixels per lenslet and that Stanford Illum has (14,14)? And also that the resolution of views can be different, example the Stanford ones are (541,376) whereas our images are (625 , 434).

**Comment by doda42** [comment]
The differences here are in how the raw lenslet images have been decoded. The Stanford light fields you indicated were decoded using the Lytro Power Tools. They are not raw images, they have been decoded and saved as ESLF.  As with the toolbox decode, that decode makes decisions around how to deal with lenslet/pixel alignment, and interpolates to some pixel count that is separate from the actual number of pixels and lenslets in the camera.

An upcoming toolbox feature will correctly guess the lenslet pitch of ESLF files more of the time, e.g. when reading toolbox-decoded eslfs. Right now, you need to tell it the correct pitch a lot of the time.

In detail: I think all the Illums have pixel pitch 1.4 microns, lenslet pitch 20 microns, meaning there are 20/1.4 = 14.2857... pixels per lenslet in the raw images.  Decoding to a rational pitch is impractical, so every decoder I'm aware of chooses an integer pitch and interpolates. Some use 14, some use 15 pixels per lenslet.  You could use 30 if you like.

Resolution differences: How finely interpolation is carried out varies by decoder, so you get some decoded light fields with more pixels than others. Sometimes higher levels of interpolation (more pixels) are misinterpreted as corresponding directly to higher resolution (ability to resolve fine detail). These are not the same, interpolating by 2x doesn't boost your resolution 2x.

There are also decisions around where to crop images. The lenslet array is generally not perfectly rotationally aligned with the image sensor, so we get a rotated rectangular image that we could crop aggressively to remove black pixels, or less aggressively to include them. In the toolbox this decision can change based on camera focus settings, so not all light fields from the same camera will decode to the same size.  Generally this varies by only 1 or 2 pixels, but it can throw your code out if you've hard-coded the size.

Hope that helps.

**Comment by moha23** [comment]
That helps a lot, thanks! Specifically for Stanford Illum dataset, I guess they decoded to 14 pixels per lenselet, because if I use (15,15), there seems to be more black frames.

**Comment by moha23** [comment]
Hi Donald, one confusion I'm having is Stanford ESLF Illum images are already decoded and saved as ESLF, so they have probably been colour corrected? But when I decode using LFReadESLF, the decoded images are quite a bit darker than the thumbnails, I want to apply colour correction but I'm not sure that is possible because using the toolbox this is usually done during the decoding process. Am I wrong?

**Comment by doda42** [comment]
I suggest thinking of ESLF like a file format, like PNG or JPEG.  They can store colour correct images, or not.  Rectified, or not.  It's just a way to store pixels.  It's up to you to keep track of what goes into each file.

Not sure what you mean about the loaded ESLF files looking darker than the thumbnails. Which thumbnails?

You can contrast stretch a loaded light field using LFHistEqualize.

You can colour correct a light field using LFColourCorrect, though this requires you to track down a colour correction matrix, e.g. the one from the metadata that LFUtilDecodeLytroFolder uses... search for "LFColourCorrect" in LFUtilDecodeLytroFolder and you'll see DecodeOptions.ColourMatrix, .ColourBalance, and .Gamma.  These get set in LFLytroDecodeImage.m using the lytro metadata.  So if you look in the metadata for the dataset you're using, you should find the appropriate colour correction matrices.  

Quick note that colour correcting twice won't make the images twice as nice.  If you're still stuck feel free to paste links to example files....

**Comment by moha23** [comment]
Yes, I read up a little on ESLF later and understood that it's just how Lytro power tools can save decoded and processed data. 

By thumbnails I mean the images produced by Lytro power tools, they are shown as thumbnails on Stanford's dataset website, for example, from [Stanford's Illum dataset](http://lightfields.stanford.edu/flowers_plants.html), I've attached the thumbnail and one of the views decoded using LFReadESLF (Image56, category flowers&plants):

![tulip](https://user-images.githubusercontent.com/10138421/89783882-52f8ad00-db35-11ea-9de1-2170714a3be4.jpg)

I have earlier decoded my own Illum images using the toolbox and applied colour correction, the images were a bit noisy but brighter. But I wasn't sure if applying colour correction here makes sense (or is even possible) since lytro power tools probably already applies colour correction before creating an ESLF file (as far as I could figure). However I tried using Histogram Equalisation as you suggested and it looks much better. 

![view_4_4](https://user-images.githubusercontent.com/10138421/89785413-02cf1a00-db38-11ea-942c-f51ac093b3bf.png)

Do you know if these particular Stanford dataset images can be further colour corrected (metadata is provided as json files) ? Also, just excited, by when do you expect v0.6 will come out? Very eager to try out the improved colour correction  on raw LFR images. Thanks a bunch once again!

**Comment by doda42** [comment]
So the extent to which the power tools has applied colour correction is unclear to me. You may find some clarity by digging around in the metadata, and comparing the toolbox, power tools, and lytro desktop output.  From the photos you've posted, it seems like it's not doing a very good job with colour correction.

Regardless, if your intent is to get pretty images, then you can always apply more colour adjustments, even if these are manual and not based on any particular calibrated response matrices.  Think about the adjustment tools in something like photoshop or gimp, and how they can be used to enhance the appearance of photos.

**Comment by xianrui-luo** [comment]
Hi @moha23 I experienced the same issue, that the pictures are darker. I wonder what you have done to correct them?
Thank you.

**Comment by moha23** [comment]
Hi @notorious-eric, my requirements didn't really need the pictures to be 'pretty' so I didn't specifically pursue it. However, I read a few papers which work with Lytro Illum images and they mention having applied this toolbox's colour correction followed by gamma correction. Gamma correction helps quite a bit it seems. Also, you may refer to the code here https://cseweb.ucsd.edu/~viscomp/projects/LF/papers/SIGASIA16/ for the modifications they make for nicer visuals, specifically in the script 'AdjustTone.m' if I remember correctly. Hope that helps, let me know if you come up with other ideas. Thanks.

**Comment by xianrui-luo** [comment]
Thank you for your help, I will try these methods.
