### ISSUE TITLE
Extraction of depth slices

### ISSUE THREAD

**Issue by spitzbubchen** [doda42/LFToolbox#3]
Curious if the code will allow me to extract images located at different depths in order to reconstruct a 3D image?

Maybe consider also adding program features to README.md.

**Comment by doda42** [comment]
I don't think you'll be able to extract slices in the way you're thinking.  A focal stack is more like what you'll get by applying focus over a range of depths.

Thanks for the suggestion, key features are listed in README.md as of v0.5.
